FROM ubuntu:latest
MAINTAINER Alex Krushinsky <akrushin@student.unit.ua>

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y git build-essential nano vim

# docker build --tag=bonus04 .
# docker run -it --rm bonus04

# install -> vim, gcc, git
